(defun gfx-test ()
  (set-text-size 2)
  (fill-screen)
  (set-cursor 0 10)
  (with-gfx (str)
    (princ "Hello uLisp!" str)
    (terpri str)
    (terpri str)
    (princ "...on the M5Stack" str))
  nil)
